/* Wrecks screen: a browsable tree of shipwreck rare-loot-crate odds, typed
 * search narrowing/auto-expanding it - not a "pick one, see its own detail
 * panel" combo, since with only ~18 sectors / ~150 items total (see
 * backend/shipwreck_loot.py's own module docstring) the whole dataset is
 * cheap to hold client-side and browse directly, same as js/deposits.js's
 * own tree (whose tree-node/tree-row/disclosure/tree-children/tree-label
 * classes this reuses for a consistent look).
 *
 * Two modes, toggled by the mode tabs (mirrors js/recipe-panel.js's
 * Breakdown/Totals/Used-In tabs), sharing the same search box/tree:
 *   - "By Sector": Sector > loot-level header > item, for "I'm here right
 *     now, what can I get" browsing.
 *   - "By Item": Category > item > sector, for "I want X, where do I farm
 *     it" - per game_data_extract/shipwreck_loot_integration.md's original
 *     "Open questions" (itemDropOdds was already shaped for this).
 * The Patch/Blueprint checkboxes filter both. The search box matches
 * either the top-level entity's own name (sector name in Sector mode, item
 * name in Item mode) - in which case ALL of its children show - or a leaf
 * name (item name in Sector mode, sector name in Item mode), in which case
 * only matching leaves show; either way, matched branches force-expand
 * regardless of manual collapse state so results are visible without
 * clicking through the tree first.
 *
 * Read-only by design, same rationale as js/sources.js: this data is
 * derived from the game's own files (game_data_extract/shipwreck_loot.json,
 * regenerated by extract_shipwreck_loot.py), not hand-maintained.
 */
(function () {
  const modeSectorBtn = document.getElementById("wrecks-mode-sector");
  const modeItemBtn = document.getElementById("wrecks-mode-item");
  const searchInput = document.getElementById("wrecks-search");
  const treeEl = document.getElementById("wrecks-tree");
  const filterPatch = document.getElementById("wrecks-filter-patch");
  const filterBlueprint = document.getElementById("wrecks-filter-blueprint");

  let mode = "sector"; // "sector" | "item" - session-only, not persisted
  let sectorsData = null; // fetched once per mode, cached
  let itemsData = null;
  // Session-only, not persisted (unlike js/deposits.js's collapsed_nodes,
  // which is pushed to config.json) - a key's PRESENCE means expanded;
  // everything starts collapsed by default (browse the outline first),
  // and an active search force-expands matching branches regardless of
  // this set, without mutating it, so manual state survives clearing the
  // search box.
  const expandedKeys = new Set();

  function fmtPct(pct) {
    const rounded = Math.round(pct * 100) / 100;
    return `${rounded}%`;
  }

  function matchesQuery(text, q) {
    return !q || text.toLowerCase().includes(q);
  }

  // ---- node builders ----
  function makeGroupNode(key, label, tagClass, rightText) {
    return { kind: "group", key, label, tagClass, rightText, children: [] };
  }
  function makeLeafNode(label, tagClass, rightText, catBadge) {
    return { kind: "leaf", label, tagClass, rightText, catBadge };
  }
  function makeSummaryNode(label, tagClass) {
    return { kind: "summary", label, tagClass };
  }

  // ---- DOM rendering (mirrors js/deposits.js's renderNode/toggleNode -
  // same structural classes, plus a right-aligned value column and an
  // optional category badge these rows need that the deposit tree
  // doesn't) ----
  function renderTreeNode(node, forceExpand) {
    const wrapper = document.createElement("div");
    const row = document.createElement("div");
    row.className = "tree-row";
    const spacer = document.createElement("span");
    spacer.className = "disclosure";

    const mainEl = document.createElement("span");
    mainEl.className = "tree-row-main";
    if (node.catBadge) {
      const catEl = document.createElement("span");
      catEl.className = `wrecks-row-cat wrecks-row-cat-${node.catBadge}`;
      catEl.textContent = node.catBadge === "blueprint" ? "BP" : "Patch";
      mainEl.appendChild(catEl);
    }
    const labelEl = document.createElement("span");
    labelEl.className = `tree-label ${node.tagClass || ""}`;
    labelEl.textContent = node.label;
    mainEl.appendChild(labelEl);

    row.appendChild(spacer);
    row.appendChild(mainEl);

    if (node.rightText) {
      const rightEl = document.createElement("span");
      rightEl.className = "wrecks-row-pct";
      rightEl.textContent = node.rightText;
      row.appendChild(rightEl);
    }

    if (node.kind === "group") {
      wrapper.className = "tree-node";
      const collapsed = !forceExpand && !expandedKeys.has(node.key);
      if (collapsed) wrapper.classList.add("collapsed");
      row.classList.add("group");
      spacer.textContent = "▸";
      row.addEventListener("click", () => toggleNode(wrapper, node.key));
      wrapper.appendChild(row);

      const childrenEl = document.createElement("div");
      childrenEl.className = "tree-children";
      for (const child of node.children) {
        childrenEl.appendChild(renderTreeNode(child, forceExpand));
      }
      wrapper.appendChild(childrenEl);
    } else if (node.kind === "leaf") {
      wrapper.className = "tree-node leaf";
      wrapper.appendChild(row);
    } else {
      wrapper.className = "tree-node summary";
      wrapper.appendChild(row);
    }

    return wrapper;
  }

  function toggleNode(wrapper, key) {
    const collapsed = wrapper.classList.toggle("collapsed");
    if (collapsed) expandedKeys.delete(key);
    else expandedKeys.add(key);
  }

  function makeMessageRow(text) {
    return renderTreeNode(makeSummaryNode(text), false);
  }

  // ---- Sector mode: Sector > (summary lines) > loot-level header > item ----
  function buildSectorTree(q) {
    const showPatch = filterPatch.checked;
    const showBlueprint = filterBlueprint.checked;
    const roots = [];
    for (const sector of sectorsData) {
      const items = sector.items.filter((it) =>
        it.category === "blueprint" ? showBlueprint : showPatch
      );
      const sectorMatches = matchesQuery(sector.name, q);
      const visibleItems = sectorMatches
        ? items
        : items.filter((it) => matchesQuery(it.name, q));
      if (q && visibleItems.length === 0) continue;

      // Item levels actually obtainable here (not sector.loot_level_probability's
      // own crate-TARGET-level distribution, shown below in the summary line -
      // see the loot-level divider's own comment further down for why those
      // two aren't the same number): the 2-level eligibility window means
      // this can span one level below the lowest crate target.
      const itemLevels = items.map((it) => it.level);
      const levelRangeText = itemLevels.length
        ? Math.min(...itemLevels) === Math.max(...itemLevels)
          ? `L${itemLevels[0]}`
          : `L${Math.min(...itemLevels)}-L${Math.max(...itemLevels)}`
        : "";

      const sectorNode = makeGroupNode(
        `wsec|${sector.name}`,
        sector.name,
        "sector",
        levelRangeText
      );
      const crateTargets = Object.entries(sector.loot_level_probability)
        .sort((a, b) => Number(a[0]) - Number(b[0]))
        .map(([lvl, p]) => `L${lvl} ${fmtPct(p * 100)}`)
        .join(", ");
      sectorNode.children.push(
        makeSummaryNode(
          `Explo ${sector.explo_level} · max loot ${sector.max_loot_level} · crate targets: ${crateTargets}`,
          "loc_sum"
        )
      );
      sectorNode.children.push(
        makeSummaryNode(
          `Secondary materials: ${sector.secondary_material_pool.join(", ")}`,
          "loc_sum"
        )
      );

      // Grouped by loot level as a plain divider, not a nested collapsible
      // group - see the divider's own note in the item loop below for why
      // it's not annotated with a crate-odds percentage.
      let currentLevel = null;
      for (const item of visibleItems) {
        if (item.level !== currentLevel) {
          currentLevel = item.level;
          sectorNode.children.push(makeSummaryNode(`Loot level ${currentLevel}:`, "loc_sum"));
        }
        sectorNode.children.push(
          makeLeafNode(item.name, "planet", fmtPct(item.pct), item.category)
        );
      }
      roots.push(sectorNode);
    }
    return roots;
  }

  // ---- Item mode: Category > item > sector ----
  function buildItemTree(q) {
    const categories = [
      { key: "patch", label: "Patches", show: filterPatch.checked },
      { key: "blueprint", label: "Blueprints", show: filterBlueprint.checked },
    ];
    const roots = [];
    for (const cat of categories) {
      if (!cat.show) continue;
      const catNode = makeGroupNode(`wcat|${cat.key}`, cat.label, "type");
      let anyChild = false;

      for (const item of itemsData.filter((it) => it.category === cat.key)) {
        const itemMatches = matchesQuery(item.name, q);
        const sectorRows = [];
        for (const group of item.groups) {
          for (const sectorName of group.sectors) {
            sectorRows.push({ sectorName, pct: group.pct });
          }
        }
        const visibleRows = itemMatches
          ? sectorRows
          : sectorRows.filter((r) => matchesQuery(r.sectorName, q));
        if (q && visibleRows.length === 0) continue;
        anyChild = true;

        const itemNode = makeGroupNode(`witem|${item.name}`, item.name, "resource");
        itemNode.children.push(
          makeSummaryNode(
            item.obtainable
              ? `Loot level ${item.level} · best odds ${fmtPct(item.best_pct)} per rare loot crate`
              : `Loot level ${item.level} · not obtainable from any wreck crate`,
            "loc_sum"
          )
        );
        visibleRows.sort((a, b) => b.pct - a.pct || a.sectorName.localeCompare(b.sectorName));
        for (const r of visibleRows) {
          itemNode.children.push(makeLeafNode(r.sectorName, "loc_sec", fmtPct(r.pct)));
        }
        catNode.children.push(itemNode);
      }

      if (q && !anyChild) continue;
      roots.push(catNode);
    }
    return roots;
  }

  // ---- shared render/filter ----
  function render() {
    const q = searchInput.value.trim().toLowerCase();
    treeEl.innerHTML = "";

    if (!filterPatch.checked && !filterBlueprint.checked) {
      treeEl.appendChild(makeMessageRow("No categories selected."));
      return;
    }
    const roots = mode === "sector" ? buildSectorTree(q) : buildItemTree(q);
    if (!roots.length) {
      treeEl.appendChild(makeMessageRow("No matches."));
      return;
    }
    const forceExpand = q.length > 0;
    for (const node of roots) {
      treeEl.appendChild(renderTreeNode(node, forceExpand));
    }
  }

  async function ensureDataLoaded() {
    if (mode === "sector" && sectorsData === null) {
      sectorsData = await CraftMapApi.call("get_wreck_sectors");
    } else if (mode === "item" && itemsData === null) {
      itemsData = await CraftMapApi.call("get_wreck_items");
    }
  }

  async function setMode(newMode) {
    if (mode === newMode) return;
    mode = newMode;
    modeSectorBtn.classList.toggle("active", mode === "sector");
    modeItemBtn.classList.toggle("active", mode === "item");
    searchInput.placeholder = mode === "sector" ? "Filter sectors..." : "Filter items...";
    await ensureDataLoaded();
    render();
  }

  async function init() {
    await ensureDataLoaded();
    render();
    modeSectorBtn.addEventListener("click", () => setMode("sector"));
    modeItemBtn.addEventListener("click", () => setMode("item"));
    searchInput.addEventListener("input", render);
    filterPatch.addEventListener("change", render);
    filterBlueprint.addEventListener("change", render);
  }

  init();
})();
