/* Wrecks screen: a browsable tree of shipwreck rare-loot-crate odds, typed
 * search narrowing/auto-expanding it - not a "pick one, see its own detail
 * panel" combo, since with only ~18 sectors / ~150 items total (see
 * backend/shipwreck_loot.py's own module docstring) the whole dataset is
 * cheap to hold client-side and browse directly, same as js/deposits.js's
 * own tree (whose tree-node/tree-row/disclosure/tree-children/tree-label
 * classes this reuses for a consistent look).
 *
 * Two modes, toggled by the mode tabs (mirrors js/recipe-panel.js's
 * Breakdown/Totals/Used-In tabs), sharing the same search box/tree:
 *   - "By Sector": Sector > loot-level header > item, for "I'm here right
 *     now, what can I get" browsing.
 *   - "By Item": Category > item > sector, for "I want X, where do I farm
 *     it" - per game_data_extract/shipwreck_loot_integration.md's original
 *     "Open questions" (itemDropOdds was already shaped for this).
 * The Patch/Blueprint checkboxes filter both. The search box matches
 * either the top-level entity's own name (sector name in Sector mode, item
 * name in Item mode) - in which case ALL of its children show - or a leaf
 * name (item name in Sector mode, sector name in Item mode), in which case
 * only matching leaves show; either way, matched branches force-expand
 * regardless of manual collapse state so results are visible without
 * clicking through the tree first.
 *
 * Read-only by design, same rationale as js/sources.js: this data is
 * derived from the game's own files (game_data_extract/shipwreck_loot.json,
 * regenerated by extract_shipwreck_loot.py), not hand-maintained.
 */
(function () {
  const modeSectorBtn = document.getElementById("wrecks-mode-sector");
  const modeItemBtn = document.getElementById("wrecks-mode-item");
  const modeLiveBtn = document.getElementById("wrecks-mode-live");
  const searchInput = document.getElementById("wrecks-search");
  const searchRowEl = document.getElementById("wrecks-search-row");
  const treeEl = document.getElementById("wrecks-tree");
  const filterPatch = document.getElementById("wrecks-filter-patch");
  const filterBlueprint = document.getElementById("wrecks-filter-blueprint");
  const liveViewEl = document.getElementById("wrecks-live-view");
  const crateStatsRowEl = document.getElementById("wrecks-crate-stats-row");

  let mode = "sector"; // "sector" | "item" | "live" - session-only, not persisted
  let sectorsData = null; // fetched once per mode, cached
  let itemsData = null;
  // Session-only, not persisted (unlike js/deposits.js's collapsed_nodes,
  // which is pushed to config.json) - a key's PRESENCE means expanded;
  // everything starts collapsed by default (browse the outline first),
  // and an active search force-expands matching branches regardless of
  // this set, without mutating it, so manual state survives clearing the
  // search box.
  const expandedKeys = new Set();

  function fmtPct(pct) {
    const rounded = Math.round(pct * 100) / 100;
    return `${rounded}%`;
  }

  // itemDropOdds's pct is conditional on a crate already being open;
  // wreckSiteItemOdds's atLeastOnePct folds in the sector's own crate-count
  // mix (Big wrecks average ~4x more crates than Small - see
  // shipwreck_loot_integration.md), so pairing them answers both "given I
  // find a crate" and "walking this whole wreck site". atLeastOnePct is
  // missing (null) for the handful of items marked unobtainable, which
  // backend/shipwreck_loot.py never gives a wreckSiteItemOdds entry at all.
  function fmtOdds(pct, atLeastOnePct) {
    const crateText = fmtPct(pct);
    return atLeastOnePct == null ? crateText : `${crateText} · ${fmtPct(atLeastOnePct)}/site`;
  }

  function matchesQuery(text, q) {
    return !q || text.toLowerCase().includes(q);
  }

  // "62% Small · 38% Big" - the ONE thing that actually varies by sector
  // (see backend/shipwreck_loot.py's wreck_size_counts docstring): a
  // sector's own generation-table mix of wreck-size variants, which drives
  // how often you run into a Big wreck (worth ~4x a Small wreck's own
  // crate count - see crate_spawn_by_size's docstring) versus a Small one
  // here, as opposed to what a wreck of a given size itself yields (that
  // part is sector-invariant - see renderCrateStatsRow below).
  function formatSizeDistribution(counts) {
    const total = counts && Object.values(counts).reduce((a, b) => a + b, 0);
    if (!total) return "";
    return ["Big", "Small"]
      .filter((size) => counts[size])
      .map((size) => `${Math.round((counts[size] / total) * 100)}% ${size}`)
      .join(" · ");
  }

  // The rare-crate-odds-by-wreck-SIZE figures ("avg Y/Big wreck, Z/Small
  // wreck") are identical in every sector (crate_spawn_by_size's own
  // docstring) - shown once here, above the sector list, instead of
  // repeated inside all ~18 sector nodes. Populated once sectorsData is
  // fetched (see ensureDataLoaded) since any sector's own bySize figures
  // are the shared, sector-invariant ones. Uses "total" (debris field +
  // the hull piece's own always-on secondary generation pass) since that's
  // the real total for the wreck, not just what's scattered loose around
  // it.
  function renderCrateStatsRow() {
    crateStatsRowEl.innerHTML = "";
    const bySize = sectorsData && sectorsData[0] && sectorsData[0].crate_spawn_by_size;
    if (!bySize) return;
    const header = document.createElement("div");
    header.textContent =
      "Rare crate odds by wreck size (same in every sector - only the Big/Small mix shown per-sector below varies):";
    crateStatsRowEl.appendChild(header);
    for (const size of ["Big", "Small"]) {
      const stats = bySize[size];
      if (!stats) continue;
      const total = stats.total;
      const line = document.createElement("div");
      line.textContent =
        `${size} wreck: ${fmtPct(stats.at_least_one * 100)} chance of ≥1 in the debris ` +
        `field alone (avg ${stats.expected_count.toFixed(2)}) · ${fmtPct(total.at_least_one * 100)} ` +
        `chance of ≥1 total (avg ${total.expected_count.toFixed(2)})`;
      crateStatsRowEl.appendChild(line);
    }
  }

  // ---- node builders ----
  function makeGroupNode(key, label, tagClass, rightText) {
    return { kind: "group", key, label, tagClass, rightText, children: [] };
  }
  function makeLeafNode(label, tagClass, rightText, catBadge) {
    return { kind: "leaf", label, tagClass, rightText, catBadge };
  }
  function makeSummaryNode(label, tagClass) {
    return { kind: "summary", label, tagClass };
  }

  // ---- DOM rendering (mirrors js/deposits.js's renderNode/toggleNode -
  // same structural classes, plus a right-aligned value column and an
  // optional category badge these rows need that the deposit tree
  // doesn't) ----
  function renderTreeNode(node, forceExpand) {
    const wrapper = document.createElement("div");
    const row = document.createElement("div");
    row.className = "tree-row";
    const spacer = document.createElement("span");
    spacer.className = "disclosure";

    const mainEl = document.createElement("span");
    mainEl.className = "tree-row-main";
    if (node.catBadge) {
      const catEl = document.createElement("span");
      catEl.className = `wrecks-row-cat wrecks-row-cat-${node.catBadge}`;
      catEl.textContent = node.catBadge === "blueprint" ? "BP" : "Patch";
      mainEl.appendChild(catEl);
    }
    const labelEl = document.createElement("span");
    labelEl.className = `tree-label ${node.tagClass || ""}`;
    labelEl.textContent = node.label;
    mainEl.appendChild(labelEl);

    row.appendChild(spacer);
    row.appendChild(mainEl);

    if (node.rightText) {
      const rightEl = document.createElement("span");
      rightEl.className = "wrecks-row-pct";
      rightEl.textContent = node.rightText;
      row.appendChild(rightEl);
    }

    if (node.kind === "group") {
      wrapper.className = "tree-node";
      const collapsed = !forceExpand && !expandedKeys.has(node.key);
      if (collapsed) wrapper.classList.add("collapsed");
      row.classList.add("group");
      spacer.textContent = "▸";
      row.addEventListener("click", () => toggleNode(wrapper, node.key));
      wrapper.appendChild(row);

      const childrenEl = document.createElement("div");
      childrenEl.className = "tree-children";
      for (const child of node.children) {
        childrenEl.appendChild(renderTreeNode(child, forceExpand));
      }
      wrapper.appendChild(childrenEl);
    } else if (node.kind === "leaf") {
      wrapper.className = "tree-node leaf";
      wrapper.appendChild(row);
    } else {
      wrapper.className = "tree-node summary";
      wrapper.appendChild(row);
    }

    return wrapper;
  }

  function toggleNode(wrapper, key) {
    const collapsed = wrapper.classList.toggle("collapsed");
    if (collapsed) expandedKeys.delete(key);
    else expandedKeys.add(key);
  }

  function makeMessageRow(text) {
    return renderTreeNode(makeSummaryNode(text), false);
  }

  // ---- Sector mode: Sector > (summary lines) > loot-level header > item ----
  function buildSectorTree(q) {
    const showPatch = filterPatch.checked;
    const showBlueprint = filterBlueprint.checked;
    const roots = [];
    for (const sector of sectorsData) {
      const items = sector.items.filter((it) =>
        it.category === "blueprint" ? showBlueprint : showPatch
      );
      const sectorMatches = matchesQuery(sector.name, q);
      const visibleItems = sectorMatches
        ? items
        : items.filter((it) => matchesQuery(it.name, q));
      if (q && visibleItems.length === 0) continue;

      // Item levels actually obtainable here (not sector.loot_level_probability's
      // own crate-TARGET-level distribution, shown below in the summary line -
      // see the loot-level divider's own comment further down for why those
      // two aren't the same number): the 2-level eligibility window means
      // this can span one level below the lowest crate target.
      const itemLevels = items.map((it) => it.level);
      const levelRangeText = itemLevels.length
        ? Math.min(...itemLevels) === Math.max(...itemLevels)
          ? `L${itemLevels[0]}`
          : `L${Math.min(...itemLevels)}-L${Math.max(...itemLevels)}`
        : "";
      // Wreck-size mix on the row itself (not just the expanded summary
      // below) so it's visible without expanding - THIS is what actually
      // differs sector to sector (see formatSizeDistribution's own
      // comment); the per-size crate-count figures themselves don't, so
      // they're shown once above the whole list instead (renderCrateStatsRow).
      const sizeDistText = formatSizeDistribution(sector.wreck_size_counts);
      const rowRightText = [levelRangeText, sizeDistText].filter(Boolean).join(" · ");

      const sectorNode = makeGroupNode(
        `wsec|${sector.name}`,
        sector.name,
        "sector",
        rowRightText
      );
      const crateTargets = Object.entries(sector.loot_level_probability)
        .sort((a, b) => Number(a[0]) - Number(b[0]))
        .map(([lvl, p]) => `L${lvl} ${fmtPct(p * 100)}`)
        .join(", ");
      sectorNode.children.push(
        makeSummaryNode(
          `Explo ${sector.explo_level} · max loot ${sector.max_loot_level} · crate targets: ${crateTargets}`,
          "loc_sum"
        )
      );
      // No per-size crate-odds detail here (moved to renderCrateStatsRow,
      // above the whole list - it's the same figures in every sector, see
      // that function's own comment) - just this sector's own wreck mix,
      // which is what determines how often you actually run into the
      // higher-crate-count Big variant here.
      if (sizeDistText) {
        sectorNode.children.push(
          makeSummaryNode(`Wreck mix: ${sizeDistText}`, "loc_sum")
        );
      }
      sectorNode.children.push(
        makeSummaryNode(
          `Secondary materials: ${sector.secondary_material_pool.join(", ")}`,
          "loc_sum"
        )
      );

      // Grouped by loot level as a plain divider, not a nested collapsible
      // group - see the divider's own note in the item loop below for why
      // it's not annotated with a crate-odds percentage.
      let currentLevel = null;
      for (const item of visibleItems) {
        if (item.level !== currentLevel) {
          currentLevel = item.level;
          sectorNode.children.push(makeSummaryNode(`Loot level ${currentLevel}:`, "loc_sum"));
        }
        sectorNode.children.push(
          makeLeafNode(
            item.name,
            "planet",
            fmtOdds(item.pct, item.at_least_one_pct),
            item.category
          )
        );
      }
      roots.push(sectorNode);
    }
    return roots;
  }

  // ---- Item mode: Category > item > sector ----
  function buildItemTree(q) {
    const categories = [
      { key: "patch", label: "Patches", show: filterPatch.checked },
      { key: "blueprint", label: "Blueprints", show: filterBlueprint.checked },
    ];
    const roots = [];
    for (const cat of categories) {
      if (!cat.show) continue;
      const catNode = makeGroupNode(`wcat|${cat.key}`, cat.label, "type");
      let anyChild = false;

      for (const item of itemsData.filter((it) => it.category === cat.key)) {
        const itemMatches = matchesQuery(item.name, q);
        const sectorRows = [];
        for (const group of item.groups) {
          for (const sector of group.sectors) {
            sectorRows.push({
              sectorName: sector.name,
              pct: group.pct,
              atLeastOnePct: sector.at_least_one_pct,
            });
          }
        }
        const visibleRows = itemMatches
          ? sectorRows
          : sectorRows.filter((r) => matchesQuery(r.sectorName, q));
        if (q && visibleRows.length === 0) continue;
        anyChild = true;

        const itemNode = makeGroupNode(`witem|${item.name}`, item.name, "resource");
        const bestSiteText =
          item.best_at_least_one_pct == null
            ? ""
            : ` · best ${fmtPct(item.best_at_least_one_pct)} per wreck site`;
        itemNode.children.push(
          makeSummaryNode(
            item.obtainable
              ? `Loot level ${item.level} · best odds ${fmtPct(item.best_pct)} per rare loot crate${bestSiteText}`
              : `Loot level ${item.level} · not obtainable from any wreck crate`,
            "loc_sum"
          )
        );
        visibleRows.sort((a, b) => b.pct - a.pct || a.sectorName.localeCompare(b.sectorName));
        for (const r of visibleRows) {
          itemNode.children.push(
            makeLeafNode(r.sectorName, "loc_sec", fmtOdds(r.pct, r.atLeastOnePct))
          );
        }
        catNode.children.push(itemNode);
      }

      if (q && !anyChild) continue;
      roots.push(catNode);
    }
    return roots;
  }

  // ---- shared render/filter ----
  function render() {
    const q = searchInput.value.trim().toLowerCase();
    treeEl.innerHTML = "";

    if (!filterPatch.checked && !filterBlueprint.checked) {
      treeEl.appendChild(makeMessageRow("No categories selected."));
      return;
    }
    const roots = mode === "sector" ? buildSectorTree(q) : buildItemTree(q);
    if (!roots.length) {
      treeEl.appendChild(makeMessageRow("No matches."));
      return;
    }
    const forceExpand = q.length > 0;
    for (const node of roots) {
      treeEl.appendChild(renderTreeNode(node, forceExpand));
    }
  }

  async function ensureDataLoaded() {
    if (mode === "sector" && sectorsData === null) {
      sectorsData = await CraftMapApi.call("get_wreck_sectors");
      renderCrateStatsRow();
    } else if (mode === "item" && itemsData === null) {
      itemsData = await CraftMapApi.call("get_wreck_items");
    }
  }

  async function setMode(newMode) {
    if (mode === newMode) return;
    mode = newMode;
    modeSectorBtn.classList.toggle("active", mode === "sector");
    modeItemBtn.classList.toggle("active", mode === "item");
    modeLiveBtn.classList.toggle("active", mode === "live");
    searchRowEl.classList.toggle("hidden", mode === "live");
    treeEl.classList.toggle("hidden", mode === "live");
    crateStatsRowEl.classList.toggle("hidden", mode !== "sector");
    liveViewEl.classList.toggle("hidden", mode !== "live");
    if (mode === "live") {
      await LiveTracking.onShow();
      return;
    }
    LiveTracking.onHide();
    searchInput.placeholder = mode === "sector" ? "Filter sectors..." : "Filter items...";
    await ensureDataLoaded();
    render();
  }

  // ---- Live Tracking sub-tab: SETUP (script path) + HISTORICAL DATA
  // (all-time sightings stats) only - the live, per-cycle current-planet
  // view with bearing/distance lives in its own separate pinnable window
  // (frontend/wreck-tracker.html/js/wreck-tracker-panel.js, opened by
  // Activate below), not here, so it keeps working/visible even while
  // this tab isn't the active screen. Still polls get_live_wreck_snapshot
  // itself (status text only, snapshot body unused) - that call also
  // piggybacks a wreck_events import as a side effect (see
  // Api.get_live_wreck_snapshot's own docstring), which needs to keep
  // happening for the stats below to stay current regardless of whether
  // the separate HUD window is even open. Wrapped in its own object
  // (rather than more top-level functions in this closure) since it owns
  // a setInterval poll loop with clean start/stop lifecycle tied to
  // onShow/onHide, distinct from the static-data render() above. ----
  const LiveTracking = (function () {
    const scriptPathInput = document.getElementById("wrecks-live-script-path");
    const pythonPathInput = document.getElementById("wrecks-live-python-path");
    const saveSettingsBtn = document.getElementById("wrecks-live-save-settings-btn");
    const showOverlayBtn = document.getElementById("wrecks-live-show-overlay-btn");
    const statusEl = document.getElementById("wrecks-live-status");
    const statsEl = document.getElementById("wrecks-live-stats");
    const statsGroupRadios = document.querySelectorAll('input[name="wrecks-stats-group"]');

    const POLL_MS = 3000;
    let pollTimer = null;
    // The tracker subprocess now starts on its own with the app (see
    // main.py's on_loaded) instead of via a button here - this just
    // tracks this tab's own belief of whether it's running, for status
    // display and to know when it's died unexpectedly.
    let tracking = false;
    let sawFirstSnapshot = false;

    function fmtTime(iso) {
      if (!iso) return "";
      const d = new Date(iso);
      return isNaN(d) ? "" : d.toLocaleTimeString();
    }

    function setStatus(text, cls) {
      statusEl.textContent = text;
      statusEl.className = cls || "";
    }

    function makeRow(mainText, rightText) {
      const row = document.createElement("div");
      row.className = "source-row";
      const nameEl = document.createElement("span");
      nameEl.className = "source-row-name";
      nameEl.textContent = mainText;
      row.appendChild(nameEl);
      if (rightText) {
        const rightEl = document.createElement("span");
        rightEl.className = "wrecks-live-row-right";
        rightEl.textContent = rightText;
        row.appendChild(rightEl);
      }
      return row;
    }

    function currentStatsGroup() {
      for (const r of statsGroupRadios) if (r.checked) return r.value;
      return "planet";
    }

    async function renderStats() {
      const rows = await CraftMapApi.call("get_wreck_stats");
      statsEl.innerHTML = "";
      if (!rows.length) {
        statsEl.appendChild(makeRow("No sightings logged yet."));
        return;
      }
      const groupBy = currentStatsGroup();
      const groups = new Map(); // groupLabel -> {display_name -> {seen, looted, despawned}}
      for (const r of rows) {
        const label =
          groupBy === "sector"
            ? r.sector || "(unknown sector)"
            : groupBy === "system"
              ? r.system_name
              : `${r.system_name} - ${r.planet}`;
        const byResource = groups.get(label) || new Map();
        const key = `${r.display_name} L${r.level}`;
        const agg = byResource.get(key) || { seen: 0, looted: 0, despawned: 0 };
        agg.seen += r.seen_count;
        agg.looted += r.looted_count;
        agg.despawned += r.despawned_count;
        byResource.set(key, agg);
        groups.set(label, byResource);
      }
      for (const [label, byResource] of [...groups.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
        const header = document.createElement("div");
        header.className = "source-row source-row-header";
        header.textContent = label;
        statsEl.appendChild(header);
        for (const [resLabel, agg] of [...byResource.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
          const parts = [`${agg.seen} seen`];
          if (agg.looted) parts.push(`${agg.looted} looted`);
          if (agg.despawned) parts.push(`${agg.despawned} despawned`);
          statsEl.appendChild(makeRow(`  ${resLabel}`, parts.join(" · ")));
        }
      }
    }

    // The live snapshot FILE persists on disk across poller restarts - a
    // freshly (re)started poller's get_live_wreck_snapshot immediately
    // returns a previous session's leftover the instant it's called,
    // well before the new poller has actually attached/written anything
    // of its own (attach alone can take 1-3 minutes cold - see
    // wreck_tracker.py's own module docstring). Without checking the
    // timestamp's actual age, that leftover reads as current ("Running -
    // updated <plausible old time>") instead of "still starting up" -
    // confirmed live: this exact confusion happened, a stale
    // not-in-planet snapshot from a dead poller instance was shown as
    // if it were this session's real status. Threshold generous
    // relative to normal cycle time but far shorter than any realistic
    // attach time.
    const STALE_THRESHOLD_MS = 5000;

    function isFresh(snapshot) {
      if (!snapshot) return false;
      return Date.now() - new Date(snapshot.observed_at).getTime() < STALE_THRESHOLD_MS;
    }

    async function poll() {
      let snapshot = null;
      try {
        snapshot = await CraftMapApi.call("get_live_wreck_snapshot");
      } catch (e) {
        // CraftMapApi.call already surfaces this via the error banner
      }
      if (isFresh(snapshot)) {
        sawFirstSnapshot = true;
        setStatus(`Running - updated ${fmtTime(snapshot.observed_at)}`, "running");
      } else if (!sawFirstSnapshot) {
        setStatus("Starting up, scanning game memory (can take 1-3 minutes the first time)...", "starting");
      }
      const status = await CraftMapApi.call("get_wreck_tracking_status");
      if (!status.running && tracking) {
        // Subprocess died on its own (game not running, script path
        // wrong, etc.) - reflect that rather than keep claiming "starting".
        tracking = false;
        sawFirstSnapshot = false;
        setStatus(
          status.last_error ||
            "Tracker stopped unexpectedly - check the script path and that the game is running.",
          "error"
        );
        stopPolling();
      }
      await renderStats();
    }

    function startPolling() {
      if (pollTimer) return;
      poll();
      pollTimer = setInterval(poll, POLL_MS);
    }

    function stopPolling() {
      if (pollTimer) {
        clearInterval(pollTimer);
        pollTimer = null;
      }
    }

    // The tracker subprocess itself now starts automatically with the app
    // (see main.py's on_loaded) rather than from a button here - this
    // just makes sure it's running (start_wreck_tracking is a no-op if it
    // already is, e.g. the normal case) and opens the HUD window, doubling
    // as the manual retry when auto-start failed or wasn't configured yet.
    async function showOverlay() {
      try {
        await CraftMapApi.call("start_wreck_tracking");
      } catch (e) {
        // The transient error-banner toast already covers this (see
        // CraftMapApi.call), but also pin the reason in the tab's own
        // status line since that one doesn't auto-hide after 6s.
        const status = await CraftMapApi.call("get_wreck_tracking_status");
        setStatus(status.last_error || (e.message || String(e)), "error");
        return;
      }
      tracking = true;
      sawFirstSnapshot = false;
      setStatus("Starting up, scanning game memory (can take 1-3 minutes the first time)...", "starting");
      startPolling();
      // Opens (never hides) the separate Wreck Tracker HUD window - same
      // "always shows" semantics as the recipe panel's own '+ Queue'
      // button (see Api.show_wreck_tracker_window's own docstring). The
      // window itself keeps polling independently once open, same as the
      // queue window does while the main window is hidden.
      CraftMapApi.call("show_wreck_tracker_window");
    }

    async function saveSettings() {
      await CraftMapApi.call(
        "set_wreck_tracker_settings",
        scriptPathInput.value.trim(),
        pythonPathInput.value.trim()
      );
      // Re-launch with the new path so it takes effect right away -
      // there's no separate "Activate" button anymore to do this
      // manually now that tracking auto-starts at app launch.
      await CraftMapApi.call("stop_wreck_tracking");
      sawFirstSnapshot = false;
      try {
        await CraftMapApi.call("start_wreck_tracking");
        tracking = true;
        setStatus("Starting up, scanning game memory (can take 1-3 minutes the first time)...", "starting");
        startPolling();
      } catch (e) {
        tracking = false;
        stopPolling();
        // Transient error-banner toast already covers this (see
        // CraftMapApi.call) - also pin it in the tab's own status line.
        const status = await CraftMapApi.call("get_wreck_tracking_status");
        setStatus(status.last_error || (e.message || String(e)), "error");
      }
    }

    async function loadSettings() {
      const settings = await CraftMapApi.call("get_wreck_tracker_settings");
      scriptPathInput.value = settings.script_path || "";
      pythonPathInput.value = settings.python_path || "";
    }

    async function onShow() {
      const status = await CraftMapApi.call("get_wreck_tracking_status");
      tracking = status.running;
      if (tracking) {
        startPolling();
      } else if (status.last_error) {
        setStatus(status.last_error, "error");
      } else {
        setStatus("Not running - set a script path above, then click Show Wreck Overlay to start it.", "");
      }
      await renderStats();
    }

    function onHide() {
      stopPolling();
    }

    function init() {
      loadSettings();
      saveSettingsBtn.addEventListener("click", saveSettings);
      showOverlayBtn.addEventListener("click", showOverlay);
      for (const r of statsGroupRadios) r.addEventListener("change", renderStats);
    }

    return { init, onShow, onHide };
  })();

  async function init() {
    await ensureDataLoaded();
    render();
    modeSectorBtn.addEventListener("click", () => setMode("sector"));
    modeItemBtn.addEventListener("click", () => setMode("item"));
    modeLiveBtn.addEventListener("click", () => setMode("live"));
    searchInput.addEventListener("input", render);
    filterPatch.addEventListener("change", render);
    filterBlueprint.addEventListener("change", render);
    LiveTracking.init();
  }

  init();
})();
